# Generated by Django 5.2.3 on 2025-06-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barcode', models.BigIntegerField()),
                ('type', models.CharField(choices=[('SHOES', 'shoes')], default='SHOES', max_length=20)),
            ],
        ),
    ]
