services:
  db:
    image: postgres:17
    container_name: ls-pg
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpas1234
      POSTGRES_DB: retail
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
