# Generated by Django 5.2.3 on 2025-06-26 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_cart_alter_cartitem_product'),
        ('product', '0003_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='state',
            field=models.CharField(choices=[('IN_CART', 'In Cart'), ('PENDING', ' Payment pending'), ('CHECKED_OUT', 'Checked Out')], default='IN_CART', max_length=20),
        ),
    ]
